# Generated by Django 5.0.1 on 2025-05-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_brand_category_suppliers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='Brands',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
    ]
