# Generated by Django 5.0.1 on 2025-07-23 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_branch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='Branches',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
