# Generated by Django 5.0.1 on 2025-07-27 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_users_stockmovement_stocklevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
