# Generated by Django 5.0.1 on 2025-07-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_stocklevel_created_at_stocklevel_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklevel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
