# Generated by Django 5.0.1 on 2025-07-27 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_stocklevel_id_alter_stockmovement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='unit_cost',
        ),
    ]
