# Generated by Django 5.0.1 on 2025-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_stockmovement_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_branch_manager',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='users',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('branch_manager', 'Branch Manager')], default='user', max_length=20),
        ),
    ]
