# Generated by Django 5.0.1 on 2025-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='balance_after',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['branch'], name='inventory_s_branch__925875_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['product'], name='inventory_s_product_6a96cf_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['branch'], name='inventory_s_branch__f2a461_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product'], name='inventory_s_product_cbdc37_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['date'], name='inventory_s_date_b6e0f6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['transaction_type'], name='inventory_s_transac_6e214e_idx'),
        ),
    ]
