# Generated by Django 5.0.1 on 2026-03-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stockmovement_balance_after_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('branch', 'product', 'is_active')},
        ),
        migrations.AddIndex(
            model_name='stocklevel',
            index=models.Index(fields=['is_active'], name='inventory_s_is_acti_7ea849_idx'),
        ),
    ]
