# Generated by Django 5.0.1 on 2026-03-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stockmovement_balance_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='low_stock_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
