# Generated by Django 5.0.1 on 2026-03-22 10:05

from django.db import migrations, models


def populate_balance_before(apps, schema_editor):
    StockMovement = apps.get_model('inventory', 'StockMovement')
    movements = list(StockMovement.objects.all().order_by('branch_id', 'product_id', 'date', 'id'))
    running_balances = {}
    updates = []

    for movement in movements:
        key = (movement.branch_id, movement.product_id)
        running_balance = running_balances.get(key, 0)

        if movement.balance_after is not None:
            if movement.transaction_type == 'IN':
                balance_before = movement.balance_after - movement.quantity
                if balance_before < 0:
                    balance_before = running_balance
            else:
                balance_before = movement.balance_after + movement.quantity
        else:
            balance_before = running_balance
            if movement.transaction_type == 'IN':
                movement.balance_after = balance_before + movement.quantity
            else:
                movement.balance_after = max(balance_before - movement.quantity, 0)

        movement.balance_before = balance_before
        running_balances[key] = movement.balance_after or 0
        updates.append(movement)

    if updates:
        StockMovement.objects.bulk_update(updates, ['balance_before', 'balance_after'])


def clear_balance_before(apps, schema_editor):
    StockMovement = apps.get_model('inventory', 'StockMovement')
    StockMovement.objects.all().update(balance_before=None)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_products_low_stock_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='balance_before',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(populate_balance_before, clear_balance_before),
    ]
