# Generated by Django 5.0.1 on 2026-03-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_stocklevel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='assigned_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='inventory.branches'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin'), ('stock_manager', 'Stock Manager'), ('branch_manager', 'Branch Manager'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
