# Generated by Django 5.0.1 on 2026-03-04 11:25

from django.db import migrations


def prune_roles(apps, schema_editor):
    Users = apps.get_model('inventory', 'Users')
    for user in Users.objects.all():
        if user.user_role == 'superadmin':
            user.user_role = 'admin'
            user.save(update_fields=['user_role'])
        elif user.user_role == 'user':
            user.user_role = 'stock_manager'
            user.save(update_fields=['user_role'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_users_assigned_branch_alter_users_user_role'),
    ]

    operations = [
        migrations.RunPython(prune_roles, migrations.RunPython.noop),
    ]
