# Generated by Django 5.0.1 on 2026-03-22 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_stockmovement_balance_before'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='related_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_stock_movements', to='inventory.branches'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='transaction_group_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('BLO', 'Backload Out'), ('BLI', 'Backload In')], max_length=3),
        ),
    ]
