# Generated by Django 5.0.1 on 2026-03-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_prune_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('stock_manager', 'Stock Manager'), ('branch_manager', 'Branch Manager')], default='stock_manager', max_length=20),
        ),
    ]
