# Generated by Django 5.0.1 on 2026-03-22 12:40

from django.db import migrations, models


def ensure_stocklevel_is_active_column(apps, schema_editor):
    table_name = 'inventory_stocklevel'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"PRAGMA table_info({table_name})")
        columns = {row[1] for row in cursor.fetchall()}
        if 'is_active' not in columns:
            cursor.execute(
                f"ALTER TABLE {table_name} ADD COLUMN is_active bool NOT NULL DEFAULT 1"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_stockmovement_related_branch_and_group'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(ensure_stocklevel_is_active_column, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='stocklevel',
                    name='is_active',
                    field=models.BooleanField(default=True),
                ),
            ],
        ),
    ]
