# Generated by Codex on 2026-05-10

from django.conf import settings
from django.contrib.auth.hashers import identify_hasher
from django.db import migrations
from django.db.models import Q


def _is_encoded_password(value: str) -> bool:
    if not value:
        return False
    try:
        identify_hasher(value)
        return True
    except Exception:
        return False


def _build_unique_username(seed, auth_user_model, username_field_name, exclude_pk=None):
    username_field = auth_user_model._meta.get_field(username_field_name)
    max_length = getattr(username_field, "max_length", 150) or 150

    base = (seed or "user").strip() or "user"
    base = base[:max_length]
    candidate = base
    suffix = 1

    while True:
        lookup = {f"{username_field_name}__iexact": candidate}
        qs = auth_user_model._default_manager.filter(**lookup)
        if exclude_pk is not None:
            qs = qs.exclude(pk=exclude_pk)
        if not qs.exists():
            return candidate

        marker = f"_{suffix}"
        candidate = f"{base[: max_length - len(marker)]}{marker}"
        suffix += 1


def sync_users_to_django_auth(apps, schema_editor):
    users_model = apps.get_model("inventory", "Users")
    auth_app_label, auth_model_name = settings.AUTH_USER_MODEL.split(".")
    auth_user_model = apps.get_model(auth_app_label, auth_model_name)
    username_field_name = "username"
    email_field_name = "email"

    for app_user in users_model.objects.all().iterator():
        username_value = (getattr(app_user, "username", "") or "").strip()
        email_value = (getattr(app_user, "email", "") or "").strip()

        query = Q(**{f"{username_field_name}__iexact": username_value})
        if email_value:
            query |= Q(**{f"{email_field_name}__iexact": email_value})
        auth_user = auth_user_model._default_manager.filter(query).order_by("id").first()

        if not auth_user:
            seed = username_value or (email_value.split("@", 1)[0] if email_value else f"user{app_user.pk}")
            unique_username = _build_unique_username(seed, auth_user_model, username_field_name)
            auth_user = auth_user_model(**{username_field_name: unique_username})

        desired_username_seed = username_value or f"user{app_user.pk}"
        desired_username = _build_unique_username(
            desired_username_seed,
            auth_user_model,
            username_field_name,
            exclude_pk=auth_user.pk,
        )
        setattr(auth_user, username_field_name, desired_username)
        setattr(auth_user, email_field_name, email_value)
        auth_user.first_name = getattr(app_user, "first_name", "") or ""
        auth_user.last_name = getattr(app_user, "last_name", "") or ""
        auth_user.is_active = bool(getattr(app_user, "is_active", True))

        app_password = (getattr(app_user, "password", "") or "").strip()
        if app_password:
            if _is_encoded_password(app_password):
                auth_user.password = app_password
            else:
                auth_user.set_password(app_password)
                app_user.password = auth_user.password
                app_user.save(update_fields=["password"])

        auth_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("inventory", "0020_alter_users_user_role"),
        ("inventory", "0021_users_assigned_branch"),
    ]

    operations = [
        migrations.RunPython(sync_users_to_django_auth, migrations.RunPython.noop),
    ]
