# Generated by Codex on 2026-05-10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_sync_users_to_django_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='transaction_type',
            field=models.CharField(
                choices=[
                    ('IN', 'Stock In'),
                    ('OUT', 'Stock Out'),
                    ('BLO', 'Backload Out'),
                    ('BLI', 'Backload In'),
                    ('MIX_OUT', 'Mix Out'),
                    ('MIX_IN', 'Mix In'),
                ],
                max_length=7,
            ),
        ),
        migrations.CreateModel(
            name='StockConversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('output_quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'branch',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='stock_conversions',
                        to='inventory.branches',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='stock_conversions_created',
                        to='inventory.users',
                    ),
                ),
                (
                    'handled_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='stock_conversions_handled',
                        to='inventory.users',
                    ),
                ),
                (
                    'output_product',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='stock_conversions_output',
                        to='inventory.products',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='conversion',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='movements',
                to='inventory.stockconversion',
            ),
        ),
        migrations.CreateModel(
            name='StockConversionInput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_used', models.PositiveIntegerField()),
                (
                    'conversion',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='inputs',
                        to='inventory.stockconversion',
                    ),
                ),
                (
                    'input_product',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='stock_conversion_inputs',
                        to='inventory.products',
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='stockconversion',
            index=models.Index(fields=['branch'], name='inventory_s_branch__07cdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='stockconversion',
            index=models.Index(fields=['output_product'], name='inventory_s_output__09036c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockconversion',
            index=models.Index(fields=['created_at'], name='inventory_s_created_8b330a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockconversioninput',
            index=models.Index(fields=['conversion'], name='inventory_s_convers_afcb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='stockconversioninput',
            index=models.Index(fields=['input_product'], name='inventory_s_input_p_54a46f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockconversioninput',
            unique_together={('conversion', 'input_product')},
        ),
    ]
