# Generated by Django 5.0.1 on 2026-05-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_stock_conversion_and_mix_actions'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='stocklevel',
                    name='archived_at',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='user_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('branch_manager', 'Branch Manager')], default='user', max_length=20),
        ),
    ]
